name: Integration Test

on:
  push:
    paths:
      - "frontend"


jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Tests Integration with Github Actions.
        uses: Cyb3r-Jak3/html5validator-action
        with:
          root: frontend/
          log_level: WARN