name: HTML5 Validator for frontend

on:
  push:
    paths:
      - 'frontend/'
      - '.github/workflows/'

jobs:
  test-frontend:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Tests Integration with Github Actions.
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: frontend/
          log_level: WARN
